### ISSUE TITLE
They changed something

### ISSUE THREAD

**Issue by arye321** [ishefi/let-me-read#12]
addon stopped working ☹

**Comment by arye321** [comment]
ok I found a solution 
change the user-agent to yahoo's bot:

`Mozilla/5.0 (compatible; Yahoo! Slurp; http://help.yahoo.com/help/us/ysearch/slurp)`

**Comment by Iddoyadlin** [comment]
Want to do a PR?

**Comment by arye321** [comment]
> Want to do a PR?

I wanted to but this repo is not up to date, your Firefox version is 0.0.0.11, on here its 0.0.0.9

edit: oh theres a firefox branch... ill PR to main

**Comment by Iddoyadlin** [comment]
should be resolved...
