### ISSUE TITLE
Releasing new version for Firefox

### ISSUE THREAD

**Issue by sha-265** [ishefi/let-me-read#9]
Hi,

When the new version will be released for Firefox?
[The version](https://addons.mozilla.org/en-US/firefox/addon/let-me-read-haaretz/) in Firefox's addons website is out-of-date.

Thanks.

**Comment by lama1245** [comment]
I would like to get this as well.

**Comment by lama1245** [comment]
sha, will the code you posted work, if copied into the correct location?  Though i am struggling to find exactly where to put it

**Comment by Iddoyadlin** [comment]
yes sorry for the slow response. we'll get to it in a day or two.
Meanwhile the Chrome extension can be installed in developer mode.

**Comment by Iddoyadlin** [comment]
new firefox version is out

**Comment by lama1245** [comment]
i still get Error 403 Forbidden

Forbidden
Guru Mediation:

Details: cache-hhn4053-HHN 1605378822 3446747431
